### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'welcome.pug'

### ISSUE THREAD

**Issue by wx85745997** [HeyiMaster/nest-starter#16]
https://github.com/nest-modules/mailer/issues/569

```javascript
//template: '/welcome',
template: './welcome',
```
hope help u

**Comment by HeyiMaster** [comment]
Because you don't have a pug template named welcome

**Comment by HeyiMaster** [comment]
https://github.com/nest-modules/mailer/commit/5301beafcf9e10ff28475076468313a7319c954d

**Comment by HeyiMaster** [comment]
Upgrade @nestjs-modules/mailer to 1.6.0
