### ISSUE TITLE
修改下yarn.lock，里面有的包引用的本地的文件。

### ISSUE THREAD

**Issue by chao** [HeyiMaster/nest-starter#7]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/55872/104391338-a5257a80-557a-11eb-80d6-57e005946888.png">

这个导致，不删除了yarn.lock没办法安装。

**Comment by oneMoreTime1357** [comment]
我也是同样的问题，yarn install执行报错
`error An unexpected error occurred: "http://192.168.0.61:8080/@nestjs%2fbull/-/bull-0.1.1.tgz: connect ECONNREFUSED 192.168.0.61:8080".
info If you think this is a bug, please open a bug report with the information provided in "/Users/tal/myGithub/nest-starter/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by HeyiMaster** [comment]
好的，我在.gitignore中指定下
