### ISSUE TITLE
 TypeORM Attempts to create tables that already exist

### ISSUE THREAD

**Issue by oneMoreTime1357** [HeyiMaster/nest-starter#8]
第一次运行可以正常创建table；
再次运行程序由于已经创建了user表，开始报如下错误：
`[Nest] 84480   - 2021-02-25 2:10:43 ├F10: PM┤   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3191ms
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'users' already exists`

**Comment by HeyiMaster** [comment]
Because this table already exists
